AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Metrics/BlockLength:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: true
